openapi: 3.0.1
info:
  description: This implements the Credential Offer API as per DCP specification.
    It serves as notification facility for a holder.
  title: Credential Offer API
  version: "1"
paths:
  /v1/participants/{participantContextId}/offers:
    post:
      description: Notifies the holder about the availability of a particular credential
        for issuance
      operationId: offerCredential
      parameters:
      - in: path
        name: participantContextId
        required: true
        schema:
          type: string
      - in: header
        name: Authorization
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
              externalDocs:
                description: DCP Credential Offer API
                url: https://eclipse-dataspace-dcp.github.io/decentralized-claims-protocol
      responses:
        "204":
          description: The offer notification was successfully received.
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: Request body was malformed
        "401":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: No Authorization header was given.
        "403":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: The given authentication token could not be validated.
      tags:
      - Credential Offer API
components:
  schemas:
    ApiErrorDetail:
      type: object
      example:
        message: error message
        type: ErrorType
        path: object.error.path
        invalidValue: this value is not valid
      properties:
        invalidValue:
          type: string
        message:
          type: string
        path:
          type: string
        type:
          type: string
    JsonObject:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/JsonValue"
      properties:
        empty:
          type: boolean
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
    JsonValue:
      type: object
      properties:
        valueType:
          type: string
          enum:
          - ARRAY
          - OBJECT
          - STRING
          - NUMBER
          - "TRUE"
          - "FALSE"
          - "NULL"
  securitySchemes:
    Authentication:
      bearerFormat: JWT
      description: Self-Issued ID
      scheme: bearer
      type: http
