openapi: 3.0.1
info:
  description: This API is used to manipulate credential definitions in an Issuer
    Service
  title: Issuer Service Credential Definitions Admin API
  version: "1"
paths:
  /v1alpha/participants/{participantContextId}/credentialdefinitions:
    post:
      description: Adds a new credential definition.
      operationId: createCredentialDefinition
      parameters:
      - in: path
        name: participantContextId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CredentialDefinitionDto"
      responses:
        "201":
          description: The credential definition was created successfully.
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Request body was malformed, or the request could not be processed"
        "401":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "The request could not be completed, because either the authentication\
            \ was missing or was not valid."
        "409":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Can't create the credential definition, because a object with\
            \ the same ID already exists"
      tags:
      - Issuer Service Credential Definition Admin API
    put:
      description: Updates credential definition.
      operationId: updateCredentialDefinition
      parameters:
      - in: path
        name: participantContextId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CredentialDefinitionDto"
      responses:
        "200":
          description: The credential definition was updated successfully.
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Request body was malformed, or the request could not be processed"
        "401":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "The request could not be completed, because either the authentication\
            \ was missing or was not valid."
        "404":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: Can't update the credential definition because it was not found.
      tags:
      - Issuer Service Credential Definition Admin API
  /v1alpha/participants/{participantContextId}/credentialdefinitions/query:
    post:
      description: Gets all credential definitions for a certain query.
      operationId: queryCredentialDefinitions
      parameters:
      - in: path
        name: participantContextId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QuerySpec"
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CredentialDefinition"
          description: A list of credentials definitions.
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Request body was malformed, or the request could not be processed"
        "401":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "The request could not be completed, because either the authentication\
            \ was missing or was not valid."
      tags:
      - Issuer Service Credential Definition Admin API
  /v1alpha/participants/{participantContextId}/credentialdefinitions/{credentialDefinitionId}:
    delete:
      description: Deletes a credential definition by its ID.
      operationId: deleteCredentialDefinitionById
      parameters:
      - in: path
        name: participantContextId
        required: true
        schema:
          type: string
      - in: path
        name: credentialDefinitionId
        required: true
        schema:
          type: string
      responses:
        "204":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CredentialDefinition"
          description: The credential definition was deleted.
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Request body was malformed, or the request could not be processed"
        "401":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "The request could not be completed, because either the authentication\
            \ was missing or was not valid."
        "404":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: The credential definition was not found.
      tags:
      - Issuer Service Credential Definition Admin API
    get:
      description: Gets a credential definition by its ID.
      operationId: getCredentialDefinitionById
      parameters:
      - in: path
        name: participantContextId
        required: true
        schema:
          type: string
      - in: path
        name: credentialDefinitionId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CredentialDefinition"
          description: The credential definition was found.
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Request body was malformed, or the request could not be processed"
        "401":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "The request could not be completed, because either the authentication\
            \ was missing or was not valid."
        "404":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: The credential definition was not found.
      tags:
      - Issuer Service Credential Definition Admin API
components:
  schemas:
    ApiErrorDetail:
      type: object
      properties:
        invalidValue:
          type: object
        message:
          type: string
        path:
          type: string
        type:
          type: string
    CredentialDefinition:
      type: object
      properties:
        attestations:
          type: array
          items:
            type: string
        createdAt:
          type: integer
          format: int64
        credentialType:
          type: string
        format:
          type: string
        id:
          type: string
        jsonSchema:
          type: string
        jsonSchemaUrl:
          type: string
        mappings:
          type: array
          items:
            $ref: "#/components/schemas/MappingDefinition"
        participantContextId:
          type: string
        rules:
          type: array
          items:
            $ref: "#/components/schemas/CredentialRuleDefinition"
        validity:
          type: integer
          format: int64
    CredentialDefinitionDto:
      type: object
      properties:
        attestations:
          type: array
          items:
            type: string
        credentialType:
          type: string
        format:
          type: string
        id:
          type: string
        jsonSchema:
          type: string
        jsonSchemaUrl:
          type: string
        mappings:
          type: array
          items:
            $ref: "#/components/schemas/MappingDefinition"
        rules:
          type: array
          items:
            $ref: "#/components/schemas/CredentialRuleDefinition"
        validity:
          type: integer
          format: int64
    CredentialRuleDefinition:
      type: object
      properties:
        configuration:
          type: object
          additionalProperties:
            type: object
        type:
          type: string
    Criterion:
      type: object
      properties:
        operandLeft:
          type: object
        operandRight:
          type: object
        operator:
          type: string
    MappingDefinition:
      type: object
      properties:
        input:
          type: string
        output:
          type: string
        required:
          type: boolean
    QuerySpec:
      type: object
      properties:
        filterExpression:
          type: array
          items:
            $ref: "#/components/schemas/Criterion"
        limit:
          type: integer
          format: int32
        offset:
          type: integer
          format: int32
        sortField:
          type: string
        sortOrder:
          type: string
          enum:
          - ASC
          - DESC
