openapi: 3.0.1
info:
  description: This API is used to manage issuance processes in an Issuer Service
  title: Issuer Service Issuance Process Admin API
  version: "1"
paths:
  /v1alpha/participants/{participantContextId}/issuanceprocesses/query:
    post:
      description: Gets all issuance processes for a certain query.
      operationId: queryIssuanceProcesses
      parameters:
      - in: path
        name: participantContextId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QuerySpec"
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/IssuanceProcessDto"
          description: A list of issuance processes.
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Request body was malformed, or the request could not be processed"
        "401":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "The request could not be completed, because either the authentication\
            \ was missing or was not valid."
      tags:
      - Issuer Service Issuance Process Admin API
  /v1alpha/participants/{participantContextId}/issuanceprocesses/{issuanceProcessId}:
    get:
      description: Gets an issuance process by its ID.
      operationId: getIssuanceProcessById
      parameters:
      - in: path
        name: participantContextId
        required: true
        schema:
          type: string
      - in: path
        name: issuanceProcessId
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IssuanceProcessDto"
          description: The issuance process was found.
        "400":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "Request body was malformed, or the request could not be processed"
        "401":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: "The request could not be completed, because either the authentication\
            \ was missing or was not valid."
        "404":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApiErrorDetail"
          description: The issuance process was not found.
      tags:
      - Issuer Service Issuance Process Admin API
components:
  schemas:
    ApiErrorDetail:
      type: object
      properties:
        invalidValue:
          type: object
        message:
          type: string
        path:
          type: string
        type:
          type: string
    Criterion:
      type: object
      properties:
        operandLeft:
          type: object
        operandRight:
          type: object
        operator:
          type: string
    IssuanceProcessDto:
      type: object
      properties:
        claims:
          type: object
          additionalProperties:
            type: object
        createdAt:
          type: integer
          format: int64
        credentialDefinitions:
          type: array
          items:
            type: string
        credentialFormats:
          type: object
          additionalProperties:
            type: string
            enum:
            - VC1_0_LD
            - VC1_0_JWT
            - VC2_0_JOSE
            - VC2_0_SD_JWT
            - VC2_0_COSE
        holderId:
          type: string
        holderPid:
          type: string
        id:
          type: string
        participantContextId:
          type: string
        state:
          type: string
        updatedAt:
          type: integer
          format: int64
    QuerySpec:
      type: object
      properties:
        filterExpression:
          type: array
          items:
            $ref: "#/components/schemas/Criterion"
        limit:
          type: integer
          format: int32
        offset:
          type: integer
          format: int32
        sortField:
          type: string
        sortOrder:
          type: string
          enum:
          - ASC
          - DESC
